### ISSUE TITLE
is it compatible with python3 

### ISSUE THREAD

**Issue by Abd2z** [jb892/FaceDetection-HaarCascade#1]
Thank you  for sharing this  code.

I'm Trying to run it on python3 but got errors like the folloing
Traceback (most recent call last):
  File "Haar-cascade-test-v1.py", line 21, in <module>
    cv2.putText(img, ('Face_%03d' % i), (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,0,255), 1, cv2.CV_AA)
AttributeError: module 'cv2' has no attribute 'CV_AA'

Appreciate any suggestion 
Thank you

**Comment by jakeju92** [comment]
Hi @GooFace2 ,

Currently, this work is only working properly on python 2.7.  I'm glad that you tested it on python 3.X. It seems like this issue is highly related to the OpenCV 3.x library. I will definitely check it out and see if I can get it works on python3 this weekend. 

Bo

**Comment by jakeju92** [comment]
Hi @GooFace2 , 

I just made some small changes that fixed your issue on python3. Just pull the latest version of master and you are good to go! :D

Bo
